site_name: Numberscope
site_url: 'https://numberscope.colorado.edu/doc'
nav:
    - Overview: README.md
    - User Guide:
          - Introduction: doc/user_guide.md
          - ... | flat | src/visualizers/*
    - Extending:
          - doc/extending.md
          - doc/running-from-source.md
          - doc/making-a-visualizer.md
    - Contributing:
          - CONTRIBUTING.md
          - doc/onboarding.md
          - package.md
          - doc/working-with-git-and-github.md
          - doc/gitting-it-right.md
          - doc/code-principles.md
          - doc/code-style.md
          - doc/pull-request-checklist.md
          - doc/visual-studio-code-setup.md
    - Internal code and APIs:
          - doc/working-with-bigints.md
          - src/shared/math.md
    - Other Information:
          - ... | flat | doc/*.md
docs_dir: doc
site_dir: dist/doc
theme:
    name: readthedocs
    custom_dir: doc_theme/
    prev_next_buttons_location: both
    sticky_navigation: false
extra_css: [css/coordinate.css, css/override.css]
extra_javascript:
    - js/scroll_navigation.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
plugins:
    - awesome-pages
    - search
    - semiliterate:
          exclude_extensions:
              - '.jpg'
              - '.ttf'
              - '.ico'
              - '.spec.ts'
              - 'LICENSE.md'
          ignore_folders: [node_modules, dist, coverage, '.venv', '.git']
          ignore_hidden: false
          include_extensions: ['.png', 'math.ts']
          extract_on_copy: true
          extract_standard_markdown:
              terminate: '<!-- CUT HERE -->'
          merge_docs_dir: false
          semiliterate:
              - pattern: '\.(?:ts|json5)' # Standard in-code markup
                extract:
                    start: '^\s*/\*\*+\W?md\b' # Opening like /** md
                    stop: '^\s*\*\*/\s*$' # closing **/ by itself on a line
              - pattern: '[.](.*).generator$'
                destination: '\1'
markdown_extensions:
    - pymdownx.superfences
    - mdx_math
